# Generated by Django 5.0.8 on 2024-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_hiring_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hierarchy',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='hierarchy',
            constraint=models.UniqueConstraint(fields=('manager', 'subordinate'), name='unique_manager_subordinate'),
        ),
    ]
