# Generated by Django 5.0.8 on 2024-08-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_hierarchy_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hierarchy',
            name='unique_manager_subordinate',
        ),
    ]
