# Generated by Django 5.0.8 on 2024-08-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_hierarchy_subordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='subordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='employees.employee', unique=True),
        ),
    ]
